version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_wxcloudrun-springboot
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=wxcloudrun-springboot
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=6v8RtHbG
      - >-
        MYSQL_ADDRESS=https://sh-cynosdbmysql-grp-pl1ws2yc.sql.tencentcdb.com:21934
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
networks:
  default:
    external:
      name: wxcb0
